### ISSUE TITLE
Add support to ERC223

### ISSUE THREAD

**Issue by 3esmit** [ethereans/abstract-token#3]

**Comment by commiteth** [comment]
Current balance: 1,28274334
Contract address: 0x1813d7b08dbd3395a3f1b6fa8199e340706e7e0a
![QR Code](http://3esmit.ddns.net:3000/qr/ethereans/abstract-token/bounty/3/dfeeaae4061c2ad61aaf8d825ddfcb6f4bb22b80829523ca5fd965ce3c14b261/qr.png)
Network: Testnet
To claim this bounty sign up at [http://3esmit.ddns.net:3000](http://3esmit.ddns.net:3000)
