### ISSUE TITLE
protect aprooval race condition

### ISSUE THREAD

**Issue by 3esmit** [ethereans/abstract-token#4]

**Comment by commiteth** [comment]
Current balance: 0,00000000
Contract address: 0xfdc7cf7ff65eb5bd515c12803f1f787b1a979118
![QR Code](http://3esmit.ddns.net:3000/qr/ethereans/abstract-token/bounty/4/c95d0d611972f81e08baade8e9f2538364318392b636007311cc7c2572e7b746/qr.png)
Network: Mainnet
To claim this bounty sign up at [http://3esmit.ddns.net:3000](http://3esmit.ddns.net:3000)
