### ISSUE TITLE
erc223 compatible

### ISSUE THREAD

**Issue by 3esmit** [ethereans/abstract-token#5]

**Comment by commiteth** [comment]
Current balance: 0,00000000
Contract address: 0x4acfbbe5886bbe0ad37f40fca1232b06f15c5792
![QR Code](http://3esmit.ddns.net:3000/qr/ethereans/abstract-token/bounty/5/ef147129b4021a8f3ee77468d627f989c91da52566a79f4dd44d5b306fa9ef18/qr.png)
Network: Mainnet
To claim this bounty sign up at [http://3esmit.ddns.net:3000](http://3esmit.ddns.net:3000)
