### ISSUE TITLE
minime compatible

### ISSUE THREAD

**Issue by 3esmit** [ethereans/abstract-token#6]

**Comment by commiteth** [comment]
Current balance: 0,00000000
Contract address: 0x6593f0618bc5cd473330e196e813f2e6eaf95f50
![QR Code](http://3esmit.ddns.net:3000/qr/ethereans/abstract-token/bounty/6/46017c661b47a2230a522502920e75d9c1da63504fa47ba0443e7a987e90eba8/qr.png)
Network: Mainnet
To claim this bounty sign up at [http://3esmit.ddns.net:3000](http://3esmit.ddns.net:3000)
