### ISSUE TITLE
submit package to ethpm

### ISSUE THREAD

**Issue by 3esmit** [ethereans/abstract-token#7]

**Comment by commiteth** [comment]
Current balance: 0,00000000
Contract address: 0xed78cd1bf84a7ea5351505f861f55948de1de1f3
![QR Code](http://3esmit.ddns.net:3000/qr/ethereans/abstract-token/bounty/7/b05f9c9d09e49fe4111d2b6226ac9b377472581c3d605b58770e881755809204/qr.png)
Network: Mainnet
To claim this bounty sign up at [http://3esmit.ddns.net:3000](http://3esmit.ddns.net:3000)
