### ISSUE TITLE
add controller listeners

### ISSUE THREAD

**Issue by 3esmit** [ethereans/abstract-token#8]

**Comment by commiteth** [comment]
Current balance: 0,00000000
Contract address: 0x2eb7a466fd6bb320869ead9ec8063dfd72347cde
![QR Code](http://3esmit.ddns.net:3000/qr/ethereans/abstract-token/bounty/8/0c0d8d2440f245de3e440a5a1f5975564d2a8ab1a59aaf1d2800da81791439e3/qr.png)
Network: Mainnet
To claim this bounty sign up at [http://3esmit.ddns.net:3000](http://3esmit.ddns.net:3000)
