### ISSUE TITLE
add NATSPEC

### ISSUE THREAD

**Issue by 3esmit** [ethereans/abstract-token#9]

**Comment by commiteth** [comment]
Current balance: 0,00000000
Contract address: 0xc0954e75ba01b71410d765488f2942c7705493c7
![QR Code](http://3esmit.ddns.net:3000/qr/ethereans/abstract-token/bounty/9/59951e4601fcba6b4e93a5b1bd444656d0b6588a69aae5d2289a0bd9868f895d/qr.png)
Network: Mainnet
To claim this bounty sign up at [http://3esmit.ddns.net:3000](http://3esmit.ddns.net:3000)
